all:
     children:
         site:
             hosts:
                server:
                        ansible_connection: ssh
                        ansible_user: root
                        ansible_host: 
                        ansible_port: 22
         test:
             hosts:
                server:
                        ansible_connection: ssh
                        ansible_user: root
                        ansible_host: 
                        ansible_port: 22
